// <auto-generated />
using System;
using MeAjudaAi.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeAjudaAi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312172056_AdicionarProvedorWebhookPagamentoImpulsionamento")]
    partial class AdicionarProvedorWebhookPagamentoImpulsionamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.AreaAtendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("BairroId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CidadeInteira")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.HasIndex("CidadeId");

                    b.HasIndex("ProfissionalId", "CidadeId", "BairroId");

                    b.ToTable("areas_atendimento", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NotaAtendimento")
                        .HasColumnType("integer");

                    b.Property<int>("NotaPreco")
                        .HasColumnType("integer");

                    b.Property<int>("NotaServico")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusModeracaoComentario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicoId")
                        .IsUnique();

                    b.HasIndex("ProfissionalId", "DataCriacao");

                    b.ToTable("avaliacoes", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Bairro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId", "Nome");

                    b.ToTable("bairros", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoIbge")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIbge")
                        .IsUnique();

                    b.HasIndex("EstadoId", "Nome");

                    b.ToTable("cidades", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Especialidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ProfissaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfissaoId", "Nome");

                    b.ToTable("especialidades", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoIbge")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIbge")
                        .IsUnique();

                    b.HasIndex("UF")
                        .IsUnique();

                    b.ToTable("estados", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.FormaRecebimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoFormaRecebimento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalId", "TipoFormaRecebimento");

                    b.ToTable("formas_recebimento", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.ImpulsionamentoProfissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoReferenciaPagamento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanoImpulsionamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlanoImpulsionamentoId", "Status");

                    b.HasIndex("ProfissionalId", "Status");

                    b.ToTable("impulsionamentos_profissionais", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.PlanoImpulsionamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("QuantidadePeriodo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoPeriodo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("planos_impulsionamento", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.PortfolioFoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Legenda")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalId", "Ordem");

                    b.ToTable("portfolio_fotos", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Profissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("profissoes", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AceitaContatoPeloApp")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("NotaMediaAtendimento")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NotaMediaPreco")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NotaMediaServico")
                        .HasColumnType("numeric");

                    b.Property<string>("OutraFormaContato")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PerfilVerificado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("profissionais", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.ProfissionalEspecialidade", b =>
                {
                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EspecialidadeId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfissionalId", "EspecialidadeId");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("profissionais_especialidades", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.ProfissionalProfissao", b =>
                {
                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfissaoId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfissionalId", "ProfissaoId");

                    b.HasIndex("ProfissaoId");

                    b.ToTable("profissionais_profissoes", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("BairroId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAceite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("EspecialidadeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProfissaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ValorCombinado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.HasIndex("CidadeId");

                    b.HasIndex("EspecialidadeId");

                    b.HasIndex("ProfissaoId");

                    b.HasIndex("ClienteId", "Status");

                    b.HasIndex("ProfissionalId", "Status");

                    b.ToTable("servicos", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataUltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TipoPerfil")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.WebhookPagamentoImpulsionamentoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoReferenciaPagamento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventoExternoId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("ImpulsionamentoProfissionalId")
                        .HasColumnType("uuid");

                    b.Property<string>("MensagemResultado")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ProcessadoComSucesso")
                        .HasColumnType("boolean");

                    b.Property<string>("Provedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("StatusImpulsionamentoResultado")
                        .HasColumnType("integer");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoReferenciaPagamento");

                    b.HasIndex("EventoExternoId")
                        .IsUnique();

                    b.HasIndex("ImpulsionamentoProfissionalId");

                    b.HasIndex("Provedor");

                    b.ToTable("webhooks_pagamentos_impulsionamentos_eventos", (string)null);
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.AreaAtendimento", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.Bairro", "Bairro")
                        .WithMany("AreasAtendimento")
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MeAjudaAi.Domain.Entities.Cidade", "Cidade")
                        .WithMany("AreasAtendimento")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAjudaAi.Domain.Entities.Profissional", "Profissional")
                        .WithMany("AreasAtendimento")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");

                    b.Navigation("Cidade");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Avaliacao", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAjudaAi.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAjudaAi.Domain.Entities.Servico", "Servico")
                        .WithOne("Avaliacao")
                        .HasForeignKey("MeAjudaAi.Domain.Entities.Avaliacao", "ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Profissional");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Bairro", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.Cidade", "Cidade")
                        .WithMany("Bairros")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("MeAjudaAi.Domain.Entities.Cliente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Especialidade", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.Profissao", "Profissao")
                        .WithMany("Especialidades")
                        .HasForeignKey("ProfissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profissao");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.FormaRecebimento", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.Profissional", "Profissional")
                        .WithMany("FormasRecebimento")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.ImpulsionamentoProfissional", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.PlanoImpulsionamento", "PlanoImpulsionamento")
                        .WithMany("Impulsionamentos")
                        .HasForeignKey("PlanoImpulsionamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAjudaAi.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Impulsionamentos")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoImpulsionamento");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.PortfolioFoto", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.Profissional", "Profissional")
                        .WithMany("PortfolioFotos")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Profissional", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Profissional")
                        .HasForeignKey("MeAjudaAi.Domain.Entities.Profissional", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.ProfissionalEspecialidade", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.Especialidade", "Especialidade")
                        .WithMany("Profissionais")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAjudaAi.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Especialidades")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.ProfissionalProfissao", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.Profissao", "Profissao")
                        .WithMany("Profissionais")
                        .HasForeignKey("ProfissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAjudaAi.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Profissoes")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profissao");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Servico", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MeAjudaAi.Domain.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAjudaAi.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Servicos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeAjudaAi.Domain.Entities.Especialidade", "Especialidade")
                        .WithMany()
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MeAjudaAi.Domain.Entities.Profissao", "Profissao")
                        .WithMany()
                        .HasForeignKey("ProfissaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MeAjudaAi.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Servicos")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bairro");

                    b.Navigation("Cidade");

                    b.Navigation("Cliente");

                    b.Navigation("Especialidade");

                    b.Navigation("Profissao");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.WebhookPagamentoImpulsionamentoEvento", b =>
                {
                    b.HasOne("MeAjudaAi.Domain.Entities.ImpulsionamentoProfissional", "ImpulsionamentoProfissional")
                        .WithMany()
                        .HasForeignKey("ImpulsionamentoProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ImpulsionamentoProfissional");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Bairro", b =>
                {
                    b.Navigation("AreasAtendimento");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Cidade", b =>
                {
                    b.Navigation("AreasAtendimento");

                    b.Navigation("Bairros");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Especialidade", b =>
                {
                    b.Navigation("Profissionais");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.PlanoImpulsionamento", b =>
                {
                    b.Navigation("Impulsionamentos");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Profissao", b =>
                {
                    b.Navigation("Especialidades");

                    b.Navigation("Profissionais");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Profissional", b =>
                {
                    b.Navigation("AreasAtendimento");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Especialidades");

                    b.Navigation("FormasRecebimento");

                    b.Navigation("Impulsionamentos");

                    b.Navigation("PortfolioFotos");

                    b.Navigation("Profissoes");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Servico", b =>
                {
                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("MeAjudaAi.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Profissional");
                });
#pragma warning restore 612, 618
        }
    }
}
